### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by himenekocn** [DEAFPS/SharpTimer#29]
When using this plugin, as more and more players enter, the server memory usage will reach 3.5G and prompt a memory overflow, causing the server to crash

System: debian 11

**Comment by DEAFPS** [comment]
im aware of this issue, going to do some memory related optimizing for next update

**Comment by himenekocn** [comment]
> im aware of this issue, going to do some memory related optimizing for next update

Thank you, please fix it as soon as possible, otherwise the server will crash if it is not running for less than an hour now

**Comment by DEAFPS** [comment]
it turns out the memory leak was caused by the CSSharp function `PrintToCenterHtml` and how it handles event firing to the clients. Ive updated the latest pre-release version with a workaround that should hopefully fix the memory leak along some more memory related optimizations regarding json, mysql and http.

feel free to reopen the issue if you still are experiencing ram usage issues :)
![ezgif com-crop](https://github.com/DEAFPS/SharpTimer/assets/43534349/fc0f7cdc-70a7-44a3-b19a-0fb93883bcf2)
