### ISSUE TITLE
Chat color inconsistencies (config: sharptimer_hud_primary_color)

### ISSUE THREAD

**Issue by M-archand** [DEAFPS/SharpTimer#47]
I'm using v0.2.3 and CSS v193. For some reason certain colours do not work for `sharptimer_hud_primary_color` in chat, they end up being a random colour. However, the config defined colour still always works on the timer time.

For example, #FFFFFF (white) works fine in both chat and for the timer time. However, if I change it to #FF20EC (violet), then the timer time will be #FF20EC but for some reason the chat colour is #AF85E9 (purple) when I inspect a screenshot of it with a hex colour identifier.

If I change it to #70F0FB (a light blue), the chat colour changes to #B5B8BD (grey). I found that most colours I tested ended up being this grey color in chat.

**Comment by DEAFPS** [comment]
counter strike has a fairly limited range of usable chat colors, if the plugin fails to find a match from hex to char for your color try moving it ever so slightly on the color picker to be slightly darker or brighter. alternatively you can just use plain words for the colors instead of hex values:

darkred
purple
darkgreen
lightgreen
green
red
lightgray
orange
darkpurple
lightred
