### ISSUE TITLE
[SharpTimerERROR] Error in TimerOnTick:

### ISSUE THREAD

**Issue by Jaytks** [deafps/SharpTimer#51]
Was getting this error the past few days. I was running .3 at the time. Just updated to .4. Will check to see if error occurs still.

[SharpTimerERROR] Error in TimerOnTick: Method not found: 'Single ByRef CounterStrikeSharp.API.Core.CCSPlayerPawn
Base.get_VelocityModifier()'.

**Comment by deafps** [comment]
Fixed in 0.2.4

This happened due to schema changes in the last major cs2 update which required plugins be recompiled under the latest cs# version

Don't forget to update cs# too

**Comment by alnoisegit** [comment]
This is happening to me on the latest version of cs# (v228) and metamod (v1291). It only happens when a player drops their gun/knife but it continuously spams console with the error.

![meta version](https://github.com/deafps/SharpTimer/assets/100811921/9d76f9bd-bc09-4253-b943-0e03b87cd0d0)
![css version](https://github.com/deafps/SharpTimer/assets/100811921/c09a49d9-cbde-4871-8a30-0a5cffe6963d)
![sharptimer error](https://github.com/deafps/SharpTimer/assets/100811921/35d4bba6-0f1c-4f57-ae14-e6cbf98aa7bd)

This is on the latest version of SharpTimer.
