### ISSUE TITLE
[SharpTimerERROR] Error in TimerOnTick: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by alnoisegit** [deafps/SharpTimer#52]
I'm getting this error in console when a player drops a weapon. This is happening on the latest version of cs# (v228) and metamod (v1291).

![meta version](https://github.com/deafps/SharpTimer/assets/100811921/efafd0c6-11ce-4edf-ad0b-0dc77130d2c3)
![css version](https://github.com/deafps/SharpTimer/assets/100811921/af827667-4f31-48e3-ad4c-61553851c58c)
![error](https://github.com/deafps/SharpTimer/assets/100811921/1d39649f-09fd-4567-8cb1-9b3051aaf08a)

I'm also on the latest version of SharpTimer.

**Comment by deafps** [comment]
thx for pointing this out!

should be fixed in next release, for now you can either disable players dropping their knife or set sharptimer_force_knife_speed to false (make sure to check the mapexecs too if you use them)

https://github.com/deafps/SharpTimer/commit/d938f72a0661822b5f258bd6d45a4f209929b251
